### ISSUE TITLE
Feature request: helm-perldoc thing-at-point

### ISSUE THREAD

**Issue by CeleritasCelery** [emacsorphanage/emacs-helm-perldoc#23]
I was building a perl5 layer for Spacemacs and the one thing that kept me from adding this package was the lack of "helm-perldoc symbol-at-point" function. In other words it pulls up the perldoc for the symbol under point. Would be a great addition to the package.

**Comment by syohex** [comment]
Please check latest code and #24. `helm-perldoc-at-point`
